name: lojavirtualapp
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  eva_icons_flutter: ^3.1.0
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1

  # Env
  envied: ^1.1.1

  # Provider
  provider: ^6.1.2

  # Equtable
  equatable: ^2.0.5

  # Result dart
  result_dart: ^2.0.0

  # Widget
  gap: ^3.0.1
  animated_snack_bar: ^0.4.0
  flutter_carousel_widget: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  alphabet_list_scroll_view_fix: ^2.0.2

  # Image picker
  image_picker: ^1.1.2

  # Image cropper
  image_cropper: ^9.1.0

  # Routes
  go_router: ^14.2.0

  uuid: ^4.4.2

  # Http
  dio: ^5.7.0

  # Formatar campos
  brasil_fields: ^1.15.0

  # Geolocator
  geolocator: ^13.0.4

dependency_overrides:
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
